### ISSUE TITLE
Add TLS support

### ISSUE THREAD

**Issue by joeyadams** [jhickner/smtp-mail#2]
I'm just creating this ticket to prevent duplicated work.  I'm working on TLS support right now.

First, I'm going to make a pure interface to the SMTP functionality by using a beautiful dependency injection technique:

```haskell
class Monad m => MonadSMTP m where
    putCrLf :: ByteString -> m ()
    throwSMTPError :: SMTPError -> m a
```

The protocol functions (`sendCommand`, etc.) will be in the `MonadSMTP` class:

```haskell
sendCommand :: MonadSMTP m => Command -> m (ReplyCode, ByteString)
```

And the caller will provide a MonadSMTP instance that provides all of the requested capabilities.

This has [several] benefits:

 * Isolates the pure code from side effects, simplifying reasoning

 * Lets us operate on both a [Handle] and a TLS [Context] (we need to do both to support TLS)

 * Keeps subroutines from having to pass the `SMTPConnection` down the call chain.  A Reader monad would provide the same benefit.

 * Provides sufficient flexibility to implement, say, an `smtp-conduit` package

 [several]: http://xkcd.com/1070/
 [Handle]: http://www.haskell.org/ghc/docs/latest/html/libraries/base/System-IO.html#t:Handle
 [Context]: http://hackage.haskell.org/packages/archive/tls/latest/doc/html/Network-TLS.html#t:Context

**Comment by Jefffrey** [comment]
@alevy Apparently not.

**Comment by jhickner** [comment]
This fork has has seen a lot more development progress. Check it out, it may have what you're looking for: https://github.com/avieth/smtp-mail
