### ISSUE TITLE
Build failure with GHC-8.2

### ISSUE THREAD

**Issue by phadej** [jhickner/smtp-mail#27]
```
Network/Mail/SMTP/Auth.hs:42:31: error:
    • Variable not in scope:
        (<>) :: ByteString -> ByteString -> ByteString
```

I made a revision: 

Please setup a CI (and use version bounds for dependencies).

**Comment by parsonsmatt** [comment]
Patches welcome :)

**Comment by phadej** [comment]
I guess this package is unmantained. I made a patch, but nothing happened.
