### ISSUE TITLE
Cabal install not working

### ISSUE THREAD

**Issue by wonhyukchoi** [jhickner/smtp-mail#33]
On `cabal install smtp-mail`, I get...

```
[3 of 3] Compiling Network.Mail.SMTP ( Network/Mail/SMTP.hs, dist/build/Network/Mail/SMTP.o )

Network/Mail/SMTP.hs:167:50: error:
    • Variable not in scope:
        (<>) :: ByteString -> ByteString -> ByteString
    • Perhaps you meant one of these:
        ‘>’ (imported from Prelude), ‘<$>’ (imported from Prelude),
        ‘*>’ (imported from Prelude)
```
and repeated for everywhere else where `(><)` is used.

I'm assuming some dependency is not matched?

**Comment by typetetris** [comment]
Please report your `ghc` version.

Also do

```
cabal freeze
```

and report the contents of the resulting

`cabal.project.freeze`

Thanks!

**Comment by wonhyukchoi** [comment]
Hi, I was using ghc `8.0.2`. Upgrading to `8.8.3` seemed to fix the problem.
